version: '3.1'
services:
    odoo:
        image: odoo:16.0
        env_file: .env
        depends_on:
            - postgres
        ports:
            - "8069:8069"
        volumes:
            - data:/var/lib/odoo
            - ./external-addons:/odoo/external-addons
    postgres:
        image: postgres:13
        env_file: .env
        volumes:
            - db:/var/lib/postgresql/data/pgdata
volumes:
    data:
    db: